server:
  port: 10006

logging.level.io.muenchendigital.digiwf: DEBUG

spring:

# config for digiwf-spring-cloudstream-utils
# see [digiwf-spring-cloudstream-utils#getting-started](https://github.com/it-at-m/digiwf-spring-cloudstream-utils#getting-started)
# binder config
  # TODO
# function routing config
  # TODO

# kafka config
  cloud.stream.bindings.sendMessage-out-0.destination: <YOUR ALW TOPIC>
  cloud.stream.bindings.sendCorrelateMessage-out-0.destination: <YOUR DIGIWF TOPIC>
  cloud.stream.bindings.functionRouter-in-0.group: @project.artifactId@
  cloud.stream.bindings.functionRouter-in-0.destination: <YOUR ALW TOPIC> # same as sendMessage-out-0.destination

# DigiWF config
digiwf.alw:
  personeninfo:
    host: <YOUR ALW SYSTEM HOST>
    port: <YOUR ALW SYSTEM PORT>
    rest-endpoint: <YOUR REST ENDPOINT>
    basicauth:
      username: <YOUR USERNAME>
      password: <YOUR PASSWORD>
